version: '2'

services:
  spark-master:
    image: bitnami/spark:2
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - 7077:7077
      - 8080:8080
  spark-worker:
    image: bitnami/spark:2
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077